(function(root){
 const core=root.LinAlgLab&&root.LinAlgLab.matrix||(typeof module!=='undefined'?require('../core/matrix.js'):null),state={a:2,b:1,c:3,angle:32,sweeping:false,frame:null};let context;const cleanups=[],byId=id=>document.getElementById(id),on=(n,e,h)=>{n.addEventListener(e,h);cleanups.push(()=>n.removeEventListener(e,h));};
 function calculate(next=state){const eigen=core.symmetricEigen2x2(next.a,next.b,next.c),rad=next.angle*Math.PI/180,x=[Math.cos(rad),Math.sin(rad)],ax=core.multiplyVector([[next.a,next.b],[next.b,next.c]],x),size=core.norm(ax),error=size?Math.acos(Math.max(-1,Math.min(1,core.dot(x,ax)/size)))*180/Math.PI:0;return{eigen,x,ax,error};}
 function read(){['a','b','c'].forEach(key=>{const value=Number(byId(`eig${key.toUpperCase()}`).value);state[key]=Number.isFinite(value)?value:0;});state.angle=Number(byId('probeAngleSlider').value);byId('eigB2').value=state.b;byId('probeAngleVal').textContent=`${state.angle.toFixed(0)}°`;redraw();}function snap(){const degree=(calculate().eigen.angle*180/Math.PI+360)%360;state.angle=degree;byId('probeAngleSlider').value=degree;byId('probeAngleVal').textContent=`${degree.toFixed(0)}°`;redraw();}
 function toggleSweep(){state.sweeping=!state.sweeping;const label=byId('sweepBtnLabel'),icon=byId('sweepIcon');if(state.sweeping){icon.setAttribute('data-lucide','pause');label.textContent=context.state.lang==='zh'?'暂停扫描':'Pause Sweep';const step=()=>{if(!state.sweeping)return;state.angle=(state.angle+.8)%360;byId('probeAngleSlider').value=state.angle;byId('probeAngleVal').textContent=`${state.angle.toFixed(0)}°`;redraw();state.frame=requestAnimationFrame(step);};step();}else{cancelAnimationFrame(state.frame);icon.setAttribute('data-lucide','play');label.textContent=context.state.lang==='zh'?'360° 自动扫描':'360° Auto Sweep';}if(root.lucide)root.lucide.createIcons();}
 function refresh(){const data=calculate(),found=data.error<3||Math.abs(data.error-180)<3,zh=context.state.lang==='zh',badge=byId('eigenStatusBadge'),text=byId('eigenRuleText');badge.textContent=found?(zh?'🎉 已捕获特征向量！(Collinear)':'🎉 Eigenvector Discovered!'):(zh?'扫描探针角度中...':'Scanning Probe Angle...');badge.style.cssText=`background:${found?'rgba(16,185,129,.15)':'rgba(236,72,153,.15)'};color:${found?'#10b981':'#ec4899'}`;text.textContent=found?(zh?'完美对齐！测试向量 x 与 Ax 在同一直线上重合。Ax 为 x 的标量缩放倍数（即特征值 λ）。':'Perfect alignment! Probe x and Ax are collinear. Ax is scalar multiple of x.'):(zh?`探针向量 x 与 Ax 存在 ${data.error.toFixed(1)}° 偏角。继续拖动或自动扫描！`:`Probe x and Ax differ in direction by ${data.error.toFixed(1)}°. Rotate to find eigenvectors.`);const label=byId('sweepBtnLabel');if(label)label.textContent=state.sweeping?(zh?'暂停扫描':'Pause Sweep'):(zh?'360° 自动扫描':'360° Auto Sweep');}
 function redraw(){const canvas=byId('eigenCanvas');if(!canvas)return;const {ctx,width,height}=root.LinAlgLab.canvas.setupHiDPI(canvas),origin={x:width/2,y:height/2},scale=40,data=calculate(),angle=data.eigen.angle;ctx.clearRect(0,0,width,height);root.LinAlgLab.canvas.drawGrid(ctx,width,height,origin,scale);ctx.setLineDash([6,6]);ctx.strokeStyle='rgba(236,72,153,.4)';[angle,angle+Math.PI/2].forEach(value=>{ctx.beginPath();ctx.moveTo(origin.x-10*Math.cos(value)*scale,origin.y+10*Math.sin(value)*scale);ctx.lineTo(origin.x+10*Math.cos(value)*scale,origin.y-10*Math.sin(value)*scale);ctx.stroke();});ctx.setLineDash([]);root.LinAlgLab.canvas.drawVector(ctx,origin,data.x.map(value=>value*2),scale,'#ec4899',3.5,'Probe x');root.LinAlgLab.canvas.drawVector(ctx,origin,data.ax,scale,'#8b5cf6',3.5,'Ax');byId('eigenVal1').textContent=data.eigen.values[0].toFixed(2);byId('eigenVal2').textContent=data.eigen.values[1].toFixed(2);byId('collinearError').textContent=`${data.error.toFixed(1)}°`;refresh();}
 function init(next){destroy();context=next;['eigA','eigB','eigC','probeAngleSlider'].map(byId).forEach(node=>on(node,'input',read));on(byId('autoFindEigenBtn'),'click',snap);on(byId('autoSweepEigenBtn'),'click',toggleSweep);redraw();}function destroy(){cleanups.splice(0).forEach(remove=>remove());state.sweeping=false;if(state.frame)cancelAnimationFrame(state.frame);}const api={id:'eigen',init,redraw,refresh,destroy,calculate,snap,toggleSweep};if(typeof module!=='undefined'&&module.exports)module.exports={calculate};if(root.LinAlgLab&&root.LinAlgLab.modules)root.LinAlgLab.modules.register(api);
})(typeof globalThis!=='undefined'?globalThis:this);
