(function(root){
 const core=root.LinAlgLab&&root.LinAlgLab.matrix||(typeof module!=='undefined'?require('../core/matrix.js'):null),state={u:[3,0],v:[2,3],dragging:null};let context;const cleanups=[],byId=id=>document.getElementById(id),on=(n,e,h)=>{n.addEventListener(e,h);cleanups.push(()=>n.removeEventListener(e,h));};
 function calculate(next=state){const dot=core.dot(next.u,next.v);let projection=[0,0];try{projection=core.projection(next.v,next.u,.0001);}catch(error){}return{dot,projection,perpendicular:next.v.map((value,index)=>value-projection[index])};}
 function sync(){['pux','puy','pvx','pvy'].forEach((key,index)=>byId(`${key}Val`).textContent=[state.u[0],state.u[1],state.v[0],state.v[1]][index].toFixed(1));}function read(){state.u=[Number(byId('puxSlider').value),Number(byId('puySlider').value)];state.v=[Number(byId('pvxSlider').value),Number(byId('pvySlider').value)];sync();redraw();}
 function refresh(){const zh=context.state.lang==='zh';byId('projBadge').textContent=zh?'正交分解: v = proj_u(v) + v^⊥':'Decomposition: v = proj_u(v) + v^⊥';byId('projCalloutText').textContent=zh?'正交性校验：投影分量 proj 与垂直分量 v^⊥ 点积为 0.00 (构成精确直角三角形)。':'Orthogonality Check: proj_u(v) · v^⊥ = 0.00 (Perfect Right Angle!).';}
 function redraw(){const canvas=byId('projCanvas');if(!canvas)return;const {ctx,width,height}=root.LinAlgLab.canvas.setupHiDPI(canvas),origin={x:width/2,y:height/2},scale=40,data=calculate();ctx.clearRect(0,0,width,height);root.LinAlgLab.canvas.drawGrid(ctx,width,height,origin,scale);ctx.setLineDash([4,4]);ctx.strokeStyle='rgba(6,182,212,.3)';ctx.beginPath();ctx.moveTo(origin.x-10*state.u[0]*scale,origin.y+10*state.u[1]*scale);ctx.lineTo(origin.x+10*state.u[0]*scale,origin.y-10*state.u[1]*scale);ctx.stroke();ctx.setLineDash([]);[['u',state.u,'#3b82f6'],['v',state.v,'#f59e0b'],['proj_u(v)',data.projection,'#10b981'],['v^⊥',data.perpendicular,'#f43f5e']].forEach(([label,vector,color])=>root.LinAlgLab.canvas.drawVector(ctx,origin,vector,scale,color,3.5,label));byId('projVecVal').textContent=`[${data.projection.map(value=>value.toFixed(2)).join(', ')}]`;byId('orthoCompVal').textContent=`[${data.perpendicular.map(value=>value.toFixed(2)).join(', ')}]`;byId('dotProductVal').textContent=data.dot.toFixed(2);refresh();}
 function init(next){destroy();context=next;['puxSlider','puySlider','pvxSlider','pvySlider'].map(byId).forEach(node=>on(node,'input',read));cleanups.push(root.LinAlgLab.canvas.enableDrag(byId('projCanvas'),(point,start)=>{if(start){if(Math.hypot(point.x-state.u[0],point.y-state.u[1])<.6)state.dragging='u';else if(Math.hypot(point.x-state.v[0],point.y-state.v[1])<.6)state.dragging='v';}else if(state.dragging){const value=[Math.max(-4,Math.min(4,Number(point.x.toFixed(1)))),Math.max(-4,Math.min(4,Number(point.y.toFixed(1))))];state[state.dragging]=value;byId(`p${state.dragging}xSlider`).value=value[0];byId(`p${state.dragging}ySlider`).value=value[1];sync();redraw();}},()=>state.dragging=null));redraw();}function destroy(){cleanups.splice(0).forEach(remove=>remove());state.dragging=null;}
 const api={id:'projection',init,redraw,refresh,destroy,calculate};if(typeof module!=='undefined'&&module.exports)module.exports={calculate};if(root.LinAlgLab&&root.LinAlgLab.modules)root.LinAlgLab.modules.register(api);
})(typeof globalThis!=='undefined'?globalThis:this);
