(function (root) {
  const core = root.LinAlgLab && root.LinAlgLab.matrix || (typeof module !== 'undefined' ? require('../core/matrix.js') : null);
  const state = { u: [2, 1], v: [-1, 2], c1: 1, c2: 1, dragging: null }; let context; const cleanups = [];
  const on = (node, event, handler, options) => { node.addEventListener(event, handler, options); cleanups.push(() => node.removeEventListener(event, handler, options)); };
  const byId = id => document.getElementById(id);
  function calculate(next = state) { const result = [next.c1 * next.u[0] + next.c2 * next.v[0], next.c1 * next.u[1] + next.c2 * next.v[1]]; return { result, determinant: core.determinant([[next.u[0], next.v[0]], [next.u[1], next.v[1]]]) }; }
  function language() { return context.state.lang; }
  function sync() { ['ux', 'uy', 'vx', 'vy', 'c1', 'c2'].forEach((key, index) => { const values = [state.u[0], state.u[1], state.v[0], state.v[1], state.c1, state.c2]; byId(`${key}Val`).textContent = values[index].toFixed(1); }); }
  function read() { state.u = [Number(byId('uxSlider').value), Number(byId('uySlider').value)]; state.v = [Number(byId('vxSlider').value), Number(byId('vySlider').value)]; state.c1 = Number(byId('c1Slider').value); state.c2 = Number(byId('c2Slider').value); sync(); redraw(); }
  function refresh() { const { determinant } = calculate(); const independent = Math.abs(determinant) > .05; const zh = language() === 'zh'; const badge = byId('spanStatusBadge'); const text = byId('spanRuleText'); badge.textContent = independent ? (zh ? 'Span = 2D 平面 (线性无关)' : 'Span = 2D Plane (Linearly Independent)') : (zh ? 'Span = 1D 直线 (线性相关/退化!)' : 'Span = 1D Line (Linearly Dependent)'); badge.style.cssText = `background:${independent ? 'rgba(16, 185, 129, .15)' : 'rgba(244, 63, 94, .15)'};color:${independent ? '#10b981' : '#f43f5e'};border-color:${independent ? 'rgba(16,185,129,.4)' : 'rgba(244,63,94,.4)'}`; text.textContent = independent ? (zh ? `det([u v]) = ${determinant.toFixed(2)} ≠ 0。向量线性无关，Span 覆盖整个 2D 平面 (ℝ²)。` : `det([u v]) = ${determinant.toFixed(2)} ≠ 0. Vectors are Linearly Independent, Span covers full 2D plane (ℝ²).`) : (zh ? 'det([u v]) = 0.00。向量线性相关 (u 与 v 共线)，Span 塌缩为一条 1D 直线。' : 'det([u v]) = 0.00. Vectors are Linearly Dependent (collinear), Span collapses into a 1D line.'); }
  function redraw() { const canvas = byId('spanCanvas'); if (!canvas) return; const { ctx, width, height } = root.LinAlgLab.canvas.setupHiDPI(canvas); const origin = { x: width / 2, y: height / 2 }, scale = 40, { result, determinant } = calculate(); ctx.clearRect(0, 0, width, height); root.LinAlgLab.canvas.drawGrid(ctx, width, height, origin, scale); if (Math.abs(determinant) > .01) { ctx.beginPath(); ctx.moveTo(origin.x, origin.y); ctx.lineTo(origin.x + state.c1 * state.u[0] * scale, origin.y - state.c1 * state.u[1] * scale); ctx.lineTo(origin.x + result[0] * scale, origin.y - result[1] * scale); ctx.lineTo(origin.x + state.c2 * state.v[0] * scale, origin.y - state.c2 * state.v[1] * scale); ctx.closePath(); ctx.fillStyle = 'rgba(6,182,212,.15)'; ctx.fill(); } ['c₁u', 'c₂v', 'u', 'v', 'c₁u + c₂v'].forEach((label, index) => { const vectors = [[state.c1 * state.u[0], state.c1 * state.u[1]], [state.c2 * state.v[0], state.c2 * state.v[1]], state.u, state.v, result]; const colors = ['#06b6d4', '#8b5cf6', '#06b6d4', '#8b5cf6', '#10b981']; root.LinAlgLab.canvas.drawVector(ctx, origin, vectors[index], scale, colors[index], index < 2 ? 2 : 3.5, label); }); byId('resultVectorVal').textContent = `[${result[0].toFixed(2)}, ${result[1].toFixed(2)}]`; byId('spanDetVal').textContent = determinant.toFixed(2); refresh(); }
  function init(nextContext) { destroy(); context = nextContext; const sliders = ['uxSlider', 'uySlider', 'vxSlider', 'vySlider', 'c1Slider', 'c2Slider'].map(byId); sliders.forEach(node => on(node, 'input', read)); on(byId('makeCollinearBtn'), 'click', () => { byId('vxSlider').value = (state.u[0] * 1.5).toFixed(1); byId('vySlider').value = (state.u[1] * 1.5).toFixed(1); read(); }); cleanups.push(root.LinAlgLab.canvas.enableDrag(byId('spanCanvas'), (point, start) => { if (start) { if (Math.hypot(point.x - state.u[0], point.y - state.u[1]) < .6) state.dragging = 'u'; else if (Math.hypot(point.x - state.v[0], point.y - state.v[1]) < .6) state.dragging = 'v'; } else if (state.dragging) { const value = [Math.max(-4, Math.min(4, Number(point.x.toFixed(1)))), Math.max(-4, Math.min(4, Number(point.y.toFixed(1))))]; state[state.dragging] = value; byId(`${state.dragging}xSlider`).value = value[0]; byId(`${state.dragging}ySlider`).value = value[1]; sync(); redraw(); } }, () => { state.dragging = null; })); redraw(); }
  function destroy() { cleanups.splice(0).forEach(remove => remove()); state.dragging = null; }
  const api = { id: 'span', init, redraw, refresh, destroy, calculate };
  if (typeof module !== 'undefined' && module.exports) module.exports = { calculate };
  if (root.LinAlgLab && root.LinAlgLab.modules) root.LinAlgLab.modules.register(api);
})(typeof globalThis !== 'undefined' ? globalThis : this);
